/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_wasm: () => void;
export const __wbg_queryresult_free: (a: number, b: number) => void;
export const __wbg_get_queryresult_columns: (a: number) => [number, number];
export const __wbg_set_queryresult_columns: (a: number, b: number, c: number) => void;
export const __wbg_get_queryresult_rows: (a: number) => [number, number];
export const __wbg_set_queryresult_rows: (a: number, b: number, c: number) => void;
export const __wbg_get_queryresult_row_count: (a: number) => number;
export const __wbg_set_queryresult_row_count: (a: number, b: number) => void;
export const __wbg_executeresult_free: (a: number, b: number) => void;
export const __wbg_get_executeresult_rows_affected: (a: number) => number;
export const __wbg_set_executeresult_rows_affected: (a: number, b: number) => void;
export const __wbg_columninfo_free: (a: number, b: number) => void;
export const __wbg_get_columninfo_name: (a: number) => [number, number];
export const __wbg_set_columninfo_name: (a: number, b: number, c: number) => void;
export const __wbg_get_columninfo_data_type: (a: number) => [number, number];
export const __wbg_set_columninfo_data_type: (a: number, b: number, c: number) => void;
export const __wbg_get_columninfo_nullable: (a: number) => number;
export const __wbg_set_columninfo_nullable: (a: number, b: number) => void;
export const __wbg_tableschema_free: (a: number, b: number) => void;
export const __wbg_get_tableschema_columns: (a: number) => [number, number];
export const __wbg_set_tableschema_columns: (a: number, b: number, c: number) => void;
export const __wbg_database_free: (a: number, b: number) => void;
export const database_new: () => number;
export const database_version: (a: number) => [number, number];
export const database_list_tables: (a: number) => [number, number];
export const database_query: (a: number, b: number, c: number) => [number, number, number];
export const database_describe_table: (a: number, b: number, c: number) => [number, number, number];
export const database_execute: (a: number, b: number, c: number) => [number, number, number];
export const database_load_employees: (a: number) => [number, number, number];
export const database_load_northwind: (a: number) => [number, number, number];
export const __wbg_set_executeresult_message: (a: number, b: number, c: number) => void;
export const __wbg_set_tableschema_name: (a: number, b: number, c: number) => void;
export const __wbg_get_executeresult_message: (a: number) => [number, number];
export const __wbg_get_tableschema_name: (a: number) => [number, number];
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_3: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __externref_table_alloc: () => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
