CREATE TABLE t1(x INTEGER, y VARCHAR(8));
INSERT INTO t1 VALUES(1, 'one');
INSERT INTO t1 VALUES(2, 'two');
INSERT INTO t1 VALUES(3, 'three');

CREATE VIEW v1 AS SELECT x FROM t1 WHERE x > 1;
SELECT x FROM v1;

DROP VIEW v1;
