name: Tests and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write  # Allow pushing conformance report updates

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # For third_party/sqltest
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      
      - name: Run all tests with coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov/html/
  
  conformance-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Run SQLLogicTest suite
        run: cargo test --test sqllogictest_runner --release -- --nocapture

      - name: Run sqltest conformance suite
        run: cargo test --test sqltest_conformance --release -- --nocapture
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/sqltest_results.json
        if: always()
      
      - name: Generate conformance report
        run: |
          chmod +x scripts/generate_compliance_report.sh
          ./scripts/generate_compliance_report.sh
        if: always()

      - name: Upload conformance report
        uses: actions/upload-artifact@v4
        with:
          name: conformance-report
          path: docs/SQL1999_CONFORMANCE.md
        if: always()

      - name: Commit conformance report
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if there are changes to commit
          if git diff --quiet docs/SQL1999_CONFORMANCE.md; then
            echo "No changes to conformance report"
          else
            git add docs/SQL1999_CONFORMANCE.md
            git commit -m "Update SQL:1999 conformance report [skip ci]"
            git push
          fi
